import streamlit as st
import streamlit.components.v1 as components
import sys
import io
import time
import contextlib
import re

# --- Imports ---
try:
    from pyscf import gto, scf
    from pyscf.geomopt.geometric_solver import optimize as geom_optimize
    from rdkit import Chem
    from rdkit.Chem import AllChem
    import py3Dmol
    import numpy as np
    PYSCF_READY = True
except ImportError:
    PYSCF_READY = False

# --- Page Configuration ---
st.set_page_config(page_title="Computational Chemistry - ChemieLearn", layout="wide")

st.title("💻 Computational Chemistry")
st.markdown("### Quantum Chemistry with PySCF")

if not PYSCF_READY:
    st.error("⚠️ **Libraries missing.** Please install `pyscf`, `geometric`, `rdkit`, and `py3Dmol`.")
    st.code("pip install pyscf geometric rdkit py3Dmol", language='bash')
    st.stop()

# --- Session State Initialization ---
if 'opt_energy' not in st.session_state:
    st.session_state.opt_energy = None
if 'opt_xyz' not in st.session_state:
    st.session_state.opt_xyz = None
if 'opt_log' not in st.session_state:
    st.session_state.opt_log = None
if 'input_xyz' not in st.session_state:
    st.session_state.input_xyz = None

# --- Helper Functions ---

def strip_ansi_codes(text):
    """Remove ANSI escape sequences (colors) from string."""
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)

def rdkit_pre_optimization(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles)
        if not mol: return None, "Invalid SMILES string."
        
        mol = Chem.AddHs(mol)
        num_atoms = mol.GetNumAtoms()
        
        if num_atoms > 30:
            return None, f"**Atom limit exceeded:** {num_atoms} atoms found. Maximum allowed is 30."
        
        res = AllChem.EmbedMolecule(mol, AllChem.ETKDGv3())
        if res == -1: return None, "Could not generate 3D coordinates."
            
        try: AllChem.MMFFOptimizeMolecule(mol)
        except:
            try: AllChem.UFFOptimizeMolecule(mol)
            except: pass

        xyz_lines = [str(num_atoms), "Generated by ChemieLearn"]
        conf = mol.GetConformer()
        for i in range(num_atoms):
            atom = mol.GetAtomWithIdx(i)
            pos = conf.GetAtomPosition(i)
            xyz_lines.append(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
            
        return mol, "\n".join(xyz_lines)
    except Exception as e:
        return None, f"RDKit Error: {str(e)}"

def run_pyscf_optimization(xyz_string, method, basis):
    try:
        # Clean Geometry
        lines = xyz_string.strip().split('\n')
        geom_clean = "\n".join(lines[2:])

        # --- CAPTURE LOGS ---
        stdout_capture = io.StringIO()
        stderr_capture = io.StringIO()
        
        start_time = time.time()
        
        # Redirect both stdout and stderr
        with contextlib.redirect_stdout(stdout_capture), contextlib.redirect_stderr(stderr_capture):
            # 1. Setup Initial Calculation
            mol = gto.M(atom=geom_clean, basis=basis, unit='Angstrom', charge=0, spin=0)
            
            if method == "HF":
                mf = scf.RHF(mol)
            elif method == "B3LYP":
                mf = scf.RKS(mol)
                mf.xc = 'b3lyp'
            else:
                return None, None, "Method not supported.", "Error"

            # 2. Run Optimization
            # This returns the optimized molecule object
            mol_eq = geom_optimize(mf, convergence_set='GAU')
            
            # 3. Calculate Final Energy Accurately
            # We run a single point calculation on the optimized geometry
            # This ensures mf.e_tot is strictly correct and updated.
            mf_final = scf.RHF(mol_eq) if method == "HF" else scf.RKS(mol_eq)
            if method == "B3LYP": mf_final.xc = 'b3lyp'
            mf_final.kernel()
            final_energy = mf_final.e_tot

        end_time = time.time()
        
        # --- CONSTRUCT LOG ---
        raw_log = stdout_capture.getvalue() + "\n" + stderr_capture.getvalue()
        
        # Clean ANSI codes
        clean_log = strip_ansi_codes(raw_log)
        
        # Remove the large Geometric ASCII art logo to save space
        # It usually starts with '())))))' and ends before 'geomeTRIC started'
        clean_log = re.sub(r"(\(\)\)+.*?geomeTRIC started)", "geomeTRIC started", clean_log, flags=re.DOTALL)
            
        # Prepend Summary
        summary = f"""============================================
CALCULATION SUMMARY
============================================
Method:     {method}/{basis}
Status:     Converged
Energy:     {final_energy:.8f} Hartree
Time:       {end_time - start_time:.3f} seconds
Atoms:      {mol_eq.natm}
============================================
"""
        
        # Extract Geometry for Viewer
        coords = mol_eq.atom_coords(unit='Angstrom')
        symbols = [mol_eq.atom_symbol(i) for i in range(mol_eq.natm)]
        
        opt_xyz_lines = [str(mol_eq.natm), "Optimized Geometry"]
        for i in range(mol_eq.natm):
            opt_xyz_lines.append(f"{symbols[i]} {coords[i][0]:.6f} {coords[i][1]:.6f} {coords[i][2]:.6f}")
        
        opt_xyz = "\n".join(opt_xyz_lines)
        
        return final_energy, opt_xyz, summary
        
    except Exception as e:
        return None, None, f"PySCF Error: {str(e)}", "Error occurred."

def draw_3d(xyz_string, width=400, height=400):
    view = py3Dmol.view(width=width, height=height)
    view.addModel(xyz_string, "xyz")
    view.setStyle({'stick': {}})
    view.zoomTo()
    return view

# --- Sidebar Settings ---
st.sidebar.header("⚙️ Settings")
method = st.sidebar.selectbox("Method", ["HF", "B3LYP"], index=0)
basis = st.sidebar.selectbox("Basis Set", ["sto-3g", "6-31g"], index=0)

# --- Main Input ---
st.markdown("Enter a **SMILES** string to calculate geometry and energy.")
st.warning("⚠️ **Limit:** Maximum 30 atoms.")

smiles_input = st.text_input("SMILES Input:", placeholder="e.g. C1=CC=CC=C1 for Benzene")

# --- Process ---
col_btn, col_clear = st.columns([1, 1])

with col_btn:
    if st.button("🚀 Run Calculation"):
        if not smiles_input:
            st.warning("Please enter a SMILES string.")
        else:
            with st.spinner("1. Pre-optimizing (MMFF94s)..."):
                rdkit_mol, xyz_data = rdkit_pre_optimization(smiles_input)
            
            if not rdkit_mol:
                st.error(xyz_data)
                st.session_state.opt_energy = None
            else:
                st.session_state.input_xyz = xyz_data
                
                with st.spinner(f"2. Running PySCF Optimization ({method}/{basis})..."):
                    energy, opt_xyz, log_text = run_pyscf_optimization(xyz_data, method, basis)
                
                if energy:
                    st.session_state.opt_energy = energy
                    st.session_state.opt_xyz = opt_xyz
                    st.session_state.opt_log = log_text
                    st.success("✅ Calculation Complete!")
                else:
                    st.error(log_text)
                    st.session_state.opt_energy = None

with col_clear:
    if st.button("🗑️ Clear Results"):
        st.session_state.opt_energy = None
        st.session_state.opt_xyz = None
        st.session_state.opt_log = None
        st.session_state.input_xyz = None
        st.rerun()

# --- Display Results ---
if st.session_state.opt_energy is not None:
    st.markdown("---")
    
    if st.session_state.input_xyz:
        with st.expander("👁️ View Pre-optimized Input Structure"):
            view = draw_3d(st.session_state.input_xyz)
            components.html(view._make_html(), width=400, height=400, scrolling=False)

    tab1, tab2, tab3 = st.tabs(["📊 Results", "📜 Optimization Log", "🔬 Optimized Structure"])
    
    with tab1:
        st.metric("Final Energy", f"{st.session_state.opt_energy:.6f} Hartree")
        st.info(f"Method: {method}/{basis}")
        st.download_button(
            label="📥 Download Optimized Coordinates (.xyz)",
            data=st.session_state.opt_xyz,
            file_name=f"optimized_{smiles_input}.xyz",
            mime="text/plain"
        )
        st.text_area("Optimized Coordinates (XYZ)", st.session_state.opt_xyz, height=200)
    
    with tab2:
        st.markdown("**Calculation Output:**")
        st.code(st.session_state.opt_log, language='log')
    
    with tab3:
        view = draw_3d(st.session_state.opt_xyz)
        components.html(view._make_html(), width=500, height=400, scrolling=False)

elif st.session_state.input_xyz is not None:
    with st.expander("👁️ View Pre-optimized Input Structure"):
        view = draw_3d(st.session_state.input_xyz)
        components.html(view._make_html(), width=400, height=400, scrolling=False)