import streamlit as st
import streamlit.components.v1 as components
import sys
import io

# --- Imports ---
try:
    from pyscf import gto, scf
    from pyscf.geomopt.geometric_solver import optimize as geom_optimize
    from rdkit import Chem
    from rdkit.Chem import AllChem
    import py3Dmol
    import numpy as np
    PYSCF_READY = True
except ImportError:
    PYSCF_READY = False

# --- Page Configuration ---
st.set_page_config(page_title="Computational Chemistry - ChemieLearn", layout="wide")

st.title("💻 Computational Chemistry")
st.markdown("### Quantum Chemistry with PySCF")

if not PYSCF_READY:
    st.error("⚠️ **Libraries missing.** Please install `pyscf`, `geometric`, `rdkit`, and `py3Dmol`.")
    st.code("pip install pyscf geometric rdkit py3Dmol", language='bash')
    st.stop()

# --- Session State Initialization ---
# We store results here so they don't disappear when clicking tabs
if 'opt_energy' not in st.session_state:
    st.session_state.opt_energy = None
if 'opt_xyz' not in st.session_state:
    st.session_state.opt_xyz = None
if 'opt_log' not in st.session_state:
    st.session_state.opt_log = None
if 'input_xyz' not in st.session_state:
    st.session_state.input_xyz = None

# --- Helper Functions ---
def rdkit_pre_optimization(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles)
        if not mol: return None, "Invalid SMILES string."
        
        mol = Chem.AddHs(mol)
        num_atoms = mol.GetNumAtoms()
        
        if num_atoms > 20:
            return None, f"**Atom limit exceeded:** {num_atoms} atoms found. Maximum allowed is 20."
        
        res = AllChem.EmbedMolecule(mol, AllChem.ETKDGv3())
        if res == -1: return None, "Could not generate 3D coordinates."
            
        try: AllChem.MMFFOptimizeMolecule(mol)
        except:
            try: AllChem.UFFOptimizeMolecule(mol)
            except: pass

        xyz_lines = [str(num_atoms), "Generated by ChemieLearn"]
        conf = mol.GetConformer()
        for i in range(num_atoms):
            atom = mol.GetAtomWithIdx(i)
            pos = conf.GetAtomPosition(i)
            xyz_lines.append(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
            
        return mol, "\n".join(xyz_lines)
    except Exception as e:
        return None, f"RDKit Error: {str(e)}"

def run_pyscf_optimization(xyz_string, method, basis):
    try:
        # Clean Geometry (skip first 2 lines)
        lines = xyz_string.strip().split('\n')
        geom_clean = "\n".join(lines[2:])

        old_stdout = sys.stdout
        sys.stdout = output_buffer = io.StringIO()

        mol = gto.M(atom=geom_clean, basis=basis, unit='Angstrom', charge=0, spin=0)
        
        if method == "HF":
            mf = scf.RHF(mol)
        elif method == "B3LYP":
            mf = scf.RKS(mol)
            mf.xc = 'b3lyp'
        else:
            sys.stdout = old_stdout
            return None, None, "Method not supported."

        mol_eq = geom_optimize(mf, convergence_set='GAU')
        
        final_energy = mf.e_tot

        coords = mol_eq.atom_coords(unit='Angstrom')
        symbols = [mol_eq.atom_symbol(i) for i in range(mol_eq.natm)]
        
        opt_xyz_lines = [str(mol_eq.natm), "Optimized Geometry"]
        for i in range(mol_eq.natm):
            opt_xyz_lines.append(f"{symbols[i]} {coords[i][0]:.6f} {coords[i][1]:.6f} {coords[i][2]:.6f}")
        
        opt_xyz = "\n".join(opt_xyz_lines)
        
        sys.stdout = old_stdout
        log_output = output_buffer.getvalue()
        
        return final_energy, opt_xyz, log_output
        
    except Exception as e:
        sys.stdout = old_stdout
        return None, None, f"PySCF Error: {str(e)}"

def draw_3d(xyz_string, width=400, height=400):
    view = py3Dmol.view(width=width, height=height)
    view.addModel(xyz_string, "xyz")
    view.setStyle({'stick': {}})
    view.zoomTo()
    return view

# --- Sidebar Settings ---
st.sidebar.header("⚙️ Settings")
method = st.sidebar.selectbox("Method", ["HF", "B3LYP"], index=0)
basis = st.sidebar.selectbox("Basis Set", ["sto-3g", "6-31g"], index=0)

# --- Main Input ---
st.markdown("Enter a **SMILES** string to calculate geometry and energy.")
st.warning("⚠️ **Limit:** Maximum 20 atoms.")

examples = {"Water (3 atoms)": "O", "Methane (5 atoms)": "C", "Ethanol (9 atoms)": "CCO"}
selected = st.selectbox("Quick Examples:", [""] + list(examples.keys()))
default_smiles = examples.get(selected, "")

smiles_input = st.text_input("SMILES Input:", value=default_smiles, placeholder="e.g., O for water")

# --- Process ---
# We use columns to put the button and clear button side by side
col_btn, col_clear = st.columns([1, 1])

with col_btn:
    if st.button("🚀 Run Calculation"):
        if not smiles_input:
            st.warning("Please enter a SMILES string.")
        else:
            # Step 1: RDKit
            with st.spinner("1. Pre-optimizing (MMFF94s)..."):
                rdkit_mol, xyz_data = rdkit_pre_optimization(smiles_input)
            
            if not rdkit_mol:
                st.error(xyz_data)
                # Clear previous results if error
                st.session_state.opt_energy = None
            else:
                # Save input structure to session state
                st.session_state.input_xyz = xyz_data
                
                # Step 2: PySCF
                with st.spinner(f"2. Running PySCF Optimization ({method}/{basis})..."):
                    energy, opt_xyz, log_text = run_pyscf_optimization(xyz_data, method, basis)
                
                if energy:
                    # Save results to session state
                    st.session_state.opt_energy = energy
                    st.session_state.opt_xyz = opt_xyz
                    st.session_state.opt_log = log_text
                    st.success("✅ Calculation Complete!")
                else:
                    st.error(log_text)
                    st.session_state.opt_energy = None

with col_clear:
    # Button to clear results
    if st.button("🗑️ Clear Results"):
        st.session_state.opt_energy = None
        st.session_state.opt_xyz = None
        st.session_state.opt_log = None
        st.session_state.input_xyz = None
        st.rerun()

# --- Display Results (Outside the Button Block) ---
# This ensures results persist when clicking tabs

if st.session_state.opt_energy is not None:
    st.markdown("---")
    
    # 1. Show Input Structure
    if st.session_state.input_xyz:
        with st.expander("👁️ View Pre-optimized Input Structure"):
            view = draw_3d(st.session_state.input_xyz)
            components.html(view._make_html(), width=400, height=400, scrolling=False)

    # 2. Show Results in Tabs
    tab1, tab2, tab3 = st.tabs(["📊 Results", "📜 Optimization Log", "🔬 Optimized Structure"])
    
    with tab1:
        st.metric("Final Energy", f"{st.session_state.opt_energy:.6f} Hartree")
        st.info(f"Method: {method}/{basis}")
        st.download_button(
            label="📥 Download Optimized Coordinates (.xyz)",
            data=st.session_state.opt_xyz,
            file_name=f"optimized_{smiles_input}.xyz",
            mime="text/plain"
        )
        st.text_area("Optimized Coordinates (XYZ)", st.session_state.opt_xyz, height=200)
    
    with tab2:
        st.markdown("**Raw Output:**")
        st.code(st.session_state.opt_log, language='log')
    
    with tab3:
        view = draw_3d(st.session_state.opt_xyz)
        components.html(view._make_html(), width=500, height=400, scrolling=False)

elif st.session_state.input_xyz is not None:
    # If we have input but calculation hasn't run or failed
    with st.expander("👁️ View Pre-optimized Input Structure"):
        view = draw_3d(st.session_state.input_xyz)
        components.html(view._make_html(), width=400, height=400, scrolling=False)